(function(){var h={k:"dragonbranch-a.akamaihd.net",h:"dragonbranch-a.akamaihd.net",p:"www.dragonbranch.net",q:"cdn.dragonbranch.net",d:{u:"https://dragonbranch-a.akamaihd.net/DragonBranch/al",w:"https://dragonbranch-a.akamaihd.net/DragonBranch/gdl",A:"https://dragonbranch-a.akamaihd.net/ud",m:"https://dragonbranch-a.akamaihd.net/DragonBranch/cf",l:"https://dragonbranch-a.akamaihd.net/DragonBranch/cr",v:"https://dragonbranch-a.akamaihd.net/urlcat/uchelper/",
o:"https://dragonbranch-a.akamaihd.net/stats/",n:"//cdnjs.cloudflare.com/ajax/libs/json3/3.3.2/json3.min.js"}};function l(){for(var a=new Date,c=a.getUTCFullYear(),b=a.getUTCMonth(),a=a.getUTCDate(),c=[31,(c%4||!(c%100))&&c%400?28:29,31,30,31,30,31,31,30,31,30],d=0;d<b;d++)a+=c[d];return a}function p(a,c,b){var d=b||0,f=a.length;if(a instanceof Array){if("undefined"!==typeof Array.prototype.indexOf)return a.indexOf(c,b);if(d>=f)return-1;for(0>d&&(d=Math.max(f+d,0));d<f;d++)if(a[d]===c)return d}return-1}
function q(a,c){return function(){try{var b=arguments;"function"===typeof a&&setTimeout(function(){a.apply(c,b)},0)}catch(d){}}}
var r=function(){function a(a,b,d,f){var e=a.createElement("script");a=a.body||a.head;var g=q(d,e);e.type="text/javascript";e.src=b;e.onload=e.onreadystatechange=function(){this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(e.onload=e.onreadystatechange=null,!f&&e.parentNode&&e.parentNode.removeChild(e),g())};a&&a.appendChild(e)}return function(c,b,d,f){a(f||document,c,b,d)}}(),s={add:function(a,c,b){if(a.addEventListener)return a.addEventListener(c,b,!1);if(a.attachEvent)return a.attachEvent("on"+
c,b)},remove:function(a,c,b){if(a.removeEventListener)return a.removeEventListener(c,b,!1);if(a.detachEvent)return a.detachEvent("on"+c,b)}},t=function(){var a=/^[\d,a-f]{8}-(?:[\d,a-f]{4}-){3}[\d,a-f]{12}$/i;return function(c){return a.test(c)}}(),u=function(){var a=[/\b(ir)\/(\d+)([\d\.]+)?\b/i,/\b(opr)\/(\d+)([\d\.]+)?\b/i,/\b(lunascape)\/(\d+)([\d\.]+)?\b/i,/\b(maxthon)\/(\d+)([\d\.]+)?\b/i,/\b(yabrowser)\/(\d+)([\d\.]+)?\b/i,/\b(mrchrome)\b/i,/\b(chrome)\/(\d+)([\d\.]+)?\b/i,/\b(trident)\/(\d+)([\d\.]+)?\b/i,
/\b(msie)\s(\d+)([\d\.]+)?\b/i,/\b(firefox)\/(\d+)([\d\.]+)?\b/i,/\b(safari)\/(\d+)([\d\.]+)?\b/i,/\b(opera)\/(\d+)([\d\.]+)?\b/i];return function(c){c=(c=(c=c||window)?c.navigator:navigator)&&c.userAgent;for(var b={rawName:"Unknown",rawVersion:"0",version:0},d=0;c&&d<a.length;d++){var f=a[d].exec(c);if(f){f=f.splice(1,3);b.rawName=f[0]||"Unknown";b.rawVersion=f[1]||"0";b.version=parseInt(b.rawVersion,10);f[2]&&(b.rawVersion+=f[2]);break}}switch(b.rawName.toLowerCase()){case "mrchrome":b.name="Amigo";
break;case "opr":b.name="Opera";break;case "yabrowser":b.name="Yandex";break;case "ir":b.name="Rocket";break;case "trident":b.name="MSIE";b.version+=4;break;default:b.name=b.rawName}return b}}(),v=function(){var a=/,/g,c=[/\b(?:\d[(). -]*?){9,16}\b/,/\b[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\b/i];return function(b,d,f){var e;b instanceof Array?(e=b,b=d||window):(e=[],e.push(b),e.push.apply(e,d),b=f||window);
b=b?b.Image:Image;for(d=0;d<e.length;d++){f=e;var g=d,k;k=e[d];var m=void 0;if("string"===typeof k)a:{if(!t(k))for(m=0;m<c.length;m++)if(c[m].test(k)){m="";break a}m=k}else m=k.toString();k=encodeURIComponent(m.replace(a,"$cma;"));f[g]=k}(new b).src=h.d.o+"?"+e.shift()+"="+e.join("|,|")}}();function w(a,c){var b;"MSIE"===c.name&&(b=c.version,"Microsoft Internet Explorer"===a.navigator.appName&&(b=a.document.documentMode||("CSS1Compat"===a.document.compatMode?7:5)));return b}function x(a,c){var b,d=u(a),d=w(a,d);a.constructor&&(b=a.constructor.prototype[c],"function"!==typeof b&&(!d||8<d||"object"!==typeof b)&&(b=void 0));if(d&&8>d)try{b=a.eval("(function () {return "+c+"})()")}catch(f){}b||(b=a[c]);if(b)return 8>d?b:function(){return b.apply(a,arguments)}}var setTimeout=x(window,"setTimeout");
x(window,"clearTimeout");x(window,"setInterval");x(window,"clearInterval");
var z=x(window,"btoa"),JSON=window.JSON,C=function(){function a(a){if("function"===typeof b)return b(a);for(var f,e=0,g=c,k="";a.charAt(e|0)||(g="=",e%1);k+=g.charAt(63&f>>8-e%1*8))f=f<<8|a.charCodeAt(e+=.75);return k}var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",b=z;z=z||a;return{i:a,s:function(a){for(var b=0,e="";b<a.length;)var g=parseInt(a.charAt(b++),16)<<8|parseInt(a.charAt(b++),16)<<4|parseInt(a.charAt(b++),16),e=e+c.charAt(g>>6),e=e+c.charAt(g&63);for(;e.length%
4;)e+=c.charAt(64);return e}}}();var D=u(),E=w(window,D),F,G,H=function(a,c){function b(b){var c=b.data,f;if(E&&10>E&&"string"===typeof c)try{c=JSON.parse(c)}catch(m){c=void 0}if("object"===typeof c&&"DragonBranch"===c.b&&(b.source===a||b.source===F.contentWindow||!b.source&&"Firefox"===D.name&&"Browser"===G)&&(b=d[c.mt]))for(f=0;f<b.length;f++)q(b[f])(c)}var d={},f=x(a,"postMessage");return{send:function(a){a.b="DragonBranch";E&&10>E&&(a=JSON.stringify(a));F.src?F.contentWindow.postMessage(a,"https://"+
h.h):f(a,c.location.protocol+"//"+c.location.host)},f:function(a,b){var c=d[a];c||(c=d[a]=[]);c.push(b)},r:function(){s.add(a,"message",b)}}}(window,document);function J(a){if(!(this instanceof J))return new J(a);this.e=a}var K=function(){function a(a){for(var b=c[a.aid]&&c[a.aid].ak;b&&b.length;)q(b.shift())(a.av)}var c={},b=!1;return function(d,f){var e=d.aid,g=c[e],k=g&&g.ak;if("agir"===d.mt&&(b||(H.f("agid",a),b=!0),g||(g=c[e]={}),k||(k=g.ak=[]),k.push(f),1<k.length))return;H.send(d)}}();
J.prototype.getItem=function(a,c){var b={mt:"agir"};b.aid=this.e;b.ak=a;K(b,c)};J.prototype.setItem=function(a,c){var b={mt:"asir"};b.aid=this.e;b.ak=a;b.av=c;K(b)};function L(a){if(!(this instanceof L))return new L(a);this.e=a;this.j=[];N[a]=this}var N={};L.prototype.disable=function(){var a={mt:"dr"};a.aid=this.e;H.send(a)};L.prototype.addListener=function(a){this.j.push(a)};L.prototype.sendMessage=function(a,c){var b=N[a]&&N[a].j,d;if(b)for(d=0;d<b.length;d++)q(b[d])(c)};
function O(a){if(!(this instanceof O))return new O(a);a&&(this.message=new L(a),this.storage=new J(a))}O.prototype.product={name:"Dragon Branch",domains:{api:h.k,apicdn:h.h,web:h.p,webcdn:h.q}};O.prototype.browser=D;
O.prototype.utils=function(a,c){function b(){s.remove(a,"DOMContentLoaded",b);for(s.remove(c,"load",b);e.length;)setTimeout(e.pop(),0)}function d(a,b,c){var d=g[a];d||(d=g[a]={});if(d[b]){for(;c.length;)q(c.shift())(g[a][b]);return!0}}function f(a,b,c,e,f){var g=k[a],n=g&&g[b];g||(g=k[a]={});n||(n=g[b]=[]);n.push(f);d(a,b,n)||1<n.length||r(c,function(){e();d(a,b,n)})}var e=[],g={},k={};return{addEventListener:s.add,arrayIndexOf:p,base64EncodeHex:C.s,base64EncodeText:C.i,getNativeWindowFunction:x,
loadScript:r,log:v,ready:function(d){e.push(d);"complete"===a.readyState?b():(s.add(a,"DOMContentLoaded",b),s.add(c,"load",b))},removeEventListener:s.remove,require:function(a,b,d){var e;switch(a){case "jquery":b=b||"1";f(a,b,"//ajax.googleapis.com/ajax/libs/jquery/"+b+"/jquery.min.js",function(){g[a][b]=c.jQuery.noConflict(!0)},d);break;case "swfobject":b=b||"2";e=c.swfobject;f(a,b,"//ajax.googleapis.com/ajax/libs/swfobject/"+b+"/swfobject.js",function(){g[a][b]=c.swfobject;c.swfobject=e},d);break;
case "dataman":e="DragonBranch"+C.i(b).replace(/=/g,"")+l(),f(a,b,"//"+b+"/utils/js/"+e,function(){g[a][b]=c[e];delete c[e]},d)}}}}(document,window);O.prototype.window={name:window.name};function S(a,c,b,d,f){return function(){try{(new Function("client","defaultSettings","customSettings","flags",f))(new O(a),c,b,d)}catch(e){}}}
function T(a){for(var c=a.getElementsByTagName("script"),b=0;b<c.length;b++){var d=c[b];if(d.src&&-1<d.src.indexOf(h.d.l)){a=a.createElement("a");a.href=d.src;d.parentNode&&d.parentNode.removeChild(d);if(a.search){a=a.search;d={};a=("?"===a.charAt(0)?a.substr(1):a).split("&");for(c=0;c<a.length;c++)b=a[c].split("="),d[decodeURIComponent(b[0])]=2===b.length?decodeURIComponent(b[1]):"";if(d.g&&d.t)return O.prototype.guid=d.g,d.t}return"Browser"}}}
function U(){var a=document,c=window;function b(){for(var a=O.prototype.cat.c.slice(0,5);5>a.length;)a.push("");v("POV_2",I.concat(O.prototype.guid||"00000000-0000-0000-0000-000000000000",O.prototype.token,R,k.substr(0,1E3),Q.substr(0,1E3),m.substr(0,4E3),P.substr(0,4E3),O.prototype.user.cc,a,O.prototype.user.is),c);B=!1}function d(a){var d=a.arb||[];O.prototype.guid||(O.prototype.guid=a.g);O.prototype.user||(O.prototype.user=a.ud);O.prototype.token||(O.prototype.token=a.t);O.prototype.cat||(O.prototype.cat=
a.cd);B&&O.prototype.cat&&b();if(!(y&&A instanceof Array)){y=0;A=[];for(var e=0;e<d.length;e++)try{for(var f=d[e],g=c,k=f.wp.split("."),n=new RegExp(f.ret,f.reo||""),m=0;m<k.length;m++)g=g&&g[k[m]];g&&n.test(g)&&(y|=f.bat,f.pid&&A.push(f.pid))}catch(I){}}a=a.a;d=y;e=A;for(f=0;f<a.length;f++)g=a[f],(g.t&~d||-1!==p(e,g.pid))&&g.is&&setTimeout(S(g.id,g.ds||{},g.cs||{},g.bf||0,g.is),0)}function f(a){O.prototype.user||(O.prototype.user=a.ud);O.prototype.token||(O.prototype.token=a.t);O.prototype.cat||
(O.prototype.cat=a.cd);B&&O.prototype.cat&&b()}function e(){var a={};!O.prototype.guid||"Browser"===G&&"MSIE"!==D.name||(a.mt="gd",a.g=O.prototype.guid,H.send(a))}function g(){var b={};H.r();H.f("rd",d);H.f("cd",f);H.f("gr",e);F.src?F.parentNode||a.body.appendChild(F):(b.mt="rs",H.send(b))}G=T(a);F=a.getElementById("DragonBranch");var k=c.name||"",m=a.location.href,P=a.referrer||"",Q=a.title||"",R=(new Date).valueOf(),y,A,n,M=!0,B,I=["Dragon Branch",G,"https:"===a.location.protocol,
D.name.substr(0,1E3),D.version];(B=!F)?(n=[G],F=a.createElement("iframe"),F.id="DragonBranch",F.src=h.d.m+"?"+encodeURIComponent("g")+"="+encodeURIComponent(O.prototype.guid),F.style.width="1px",F.style.height="1px",F.style.display="none"):(n=(F.getAttribute("t")||"").split("|"),(M=-1===p(n,G))&&n.push(G));M&&(v("ITRAN_1",I.concat(O.prototype.guid||"00000000-0000-0000-0000-000000000000"),c),F.setAttribute("t",n.join("|")));"undefined"===typeof JSON||"function"!==typeof JSON.stringify||
"function"!==typeof JSON.parse?r(h.d.n,function(){O.prototype.utils.JSON=c.JSON;g()}):(O.prototype.utils.JSON=JSON,g())}window.top==window&&U();})();
